various improvements and fixes ca passphrase can now be generated by a shell function in order to allow for fancy password protection schemes such as secret sharing

diff --git a/bin/clca b/bin/clca
--- a/bin/clca
+++ b/bin/clca
@@ -2,7 +2,7 @@
 #
 # CLCA - CLI CA command utility
 #
-# Copyright (c) 2004-2005 Martin Bartosch, Cynops GmbH
+# Copyright (c) 2004-2013 Martin Bartosch, Cynops GmbH
 #
 # 2004-04-26 Martin Bartosch; Cynops GmbH <m.bartosch@cynops.de>
 #
@@ -47,12 +47,39 @@ EOF
 
 trap traphandler 2 3
 
+
+# default passphrase prompt
+# return 0 means that a passphrase has been echoed to stdout
+# return 1 means that no passphrase is to be used
+get_passphrase() {
+    local TMP
+    echo -n "Enter passphrase: " >&2
+    read -s TMP
+    echo $TMP
+}
+
+# make sure get_passphrase is only called once
+# this function sets $PASSPHRASE and exports it
+# the function is called before each reference to $PASSPHRASE
+get_passphrase_cached() {
+    if [ -z ${PASSPHRASE+x} ] ; then
+	PASSPHRASE=`get_passphrase`
+	if [ $? == 0 ] ; then
+	    export PASSPHRASE
+	else
+	    unset PASSPHRASE
+	fi
+    fi
+    return 0
+}
+
 if [ -r $CFG ] ; then
     . $CFG
 else
     echo "Configuration file $CFG not found"
     exit 1
 fi
+
 
 if [ ! -r $CNF ] ; then
     echo "OpenSSL config file $CNF not found"
@@ -96,7 +123,7 @@ fi
 
 ######################################################################
 
-VERSION="0.8"
+VERSION="0.9"
 
 showhelp()
 {
@@ -113,7 +140,7 @@ Available commands:
   list			- List certificates
   issue_crl		- Issue CRL
   certify		- Sign certificate request
-  generate		- Generate Key and issue certificate 
+  genkey		- Generate (end entity) key
   revoke		- Revoke certificate
   initialize		- Initialize CA 
   backup		- Create backup of CA state
@@ -345,7 +372,7 @@ EOF
     if [ $? = 0 ] ; then
 	$MV $1.new $1
     else
-	echo "Error: could not modify openssl.cnf"
+	echo "ERROR: could not modify openssl.cnf"
 	abort 1
     fi
 }
@@ -380,18 +407,16 @@ genkey()
     done
 	
 	if [ -z "$KEYFILE" ]; then
-		echo "you need to pass a name for the key file";
+		echo "ERROR: You need to pass a name for the key file";
 		abort 1
 	fi  
 	
 	if [ -e "$KEYFILE" ]; then
-		echo "$KEYFILE already exists - aborting";
+		echo "ERROR: $KEYFILE already exists - aborting";
 		abort 1
 	fi  
 
-	echo "generating key - enter passphrase when prompted"
-	
-	$OPENSSL genrsa -aes256 -out "$KEYFILE" $BITS 
+	$OPENSSL genrsa -aes256 -out "$KEYFILE" $BITS
 	$CHMOD 400 $KEYFILE
 	echo "key written to $KEYFILE"
 }
@@ -441,7 +466,7 @@ certify()
     done
 
     if [ ! -r "$REQ" ] ; then
-	echo "Could not read certificate request $REQ"
+	echo "ERROR: Could not read certificate request $REQ"
 	abort 1
     fi
 
@@ -478,7 +503,7 @@ certify()
 		
 		$OPENSSL x509 -in $REQ -inform $INFORM -out $INFILE -outform pem
 		if [ "$?" != 0 ] ; then
-		    echo "Conversion failed."
+		    echo "ERROR: Conversion failed."
 		    abort 1
 		fi
 	    fi
@@ -488,13 +513,13 @@ certify()
 		echo "create request and certificate for a given key"
 		
 		if [ ! -e $REQ ]; then
-			echo "pass pem encoded key as last argument."
+			echo "ERROR: pass pem encoded key as last argument."
 			abort 1;
 		fi
 		
 		export CN
 		if [ -z "$SUBJECT" ]; then
-			echo -n "enter branch name: "
+			echo -n "enter subject name: "
 			read CN		
 		else
 			CN=$SUBJECT
@@ -503,18 +528,22 @@ certify()
 		INFILE=`$MKTEMP /tmp/temp.XXXXXX`
 		topurge $INFILE
 		
-		echo "generating request - please enter passphrase when asked." 
+		echo "generating request" 
+		get_passphrase_cached
+		if [ ! -z ${PASSPHRASE+x} ] ; then
+		    OPENSSLOPT="-passin env:PASSPHRASE"
+		fi
 		
-		$OPENSSL req -new -out $INFILE -outform pem -key "$REQ" $CONFIGARG
+		$OPENSSL req -new $OPENSSLOPT -out $INFILE -outform pem -key "$REQ" $CONFIGARG
 		if [ "$?" != 0 ] ; then
-		    echo "CSR creation failed."
+		    echo "ERROR: CSR creation failed."
 		    abort 1		
 	    fi
 	    
 	    REQUESTINPUT="-in $INFILE"
 		;;
 	*)
-	    echo "Unsupported request format '$REQFORMAT' specified"
+	    echo "ERROR: Unsupported request format '$REQFORMAT' specified"
 	    abort 1
 	    ;;
     esac
@@ -537,11 +566,16 @@ certify()
     
     SERIAL=`$CAT $CADBDIR/serial`
     if [ -n "$SUBJECT" ] ; then SUBJECT="-subj '$SUBJECT'" ; fi
+    
+    get_passphrase_cached
+    if [ ! -z ${PASSPHRASE+x} ] ; then
+	OPENSSLOPT="-passin env:PASSPHRASE"
+    fi
 
-    eval $HSM_PRELOAD $OPENSSL ca $KEYARG $PROFILEARG $VALIDITY $SUBJECT -cert $CACERT -out newcert.pem -outdir $CERTDIR $CONFIGARG $REQUESTINPUT
+    eval $HSM_PRELOAD $OPENSSL ca $KEYARG $OPENSSLOPT $PROFILEARG $VALIDITY $SUBJECT -cert $CACERT -out newcert.pem -outdir $CERTDIR $CONFIGARG $REQUESTINPUT
 
     if [ "$?" != 0 ] ; then
-	echo "Certification failed."
+	echo "ERROR: Certification failed."
 	abort 1
     fi
     
@@ -572,7 +606,7 @@ revoke()
 		
 		$OPENSSL x509 -in $CERTDIR/$SERIAL.pem -subject -dates -serial -fingerprint -noout
 		if [ "$?" != 0 ] ; then
-		    echo "Could not decode X.509 certificate $CERTDIR/$SERIAL.pem. Should not happen."
+		    echo "ERROR: Could not decode X.509 certificate $CERTDIR/$SERIAL.pem. Should not happen."
 		    abort 1
 		fi
 		
@@ -583,9 +617,15 @@ revoke()
 		    KEYARG="-keyfile $ROOTKEYNAME -keyform engine -engine $ENGINE"
 		fi
 
-		$HSM_PRELOAD $OPENSSL ca $KEYARG $PROFILEARG -revoke $CERTDIR/$SERIAL.pem $CONFIGARG
+		get_passphrase_cached
+		if [ ! -z ${PASSPHRASE+x} ] ; then
+		    OPENSSLOPT="-passin env:PASSPHRASE"
+		fi
+
+
+		$HSM_PRELOAD $OPENSSL ca $KEYARG $OPENSSLOPT $PROFILEARG -revoke $CERTDIR/$SERIAL.pem $CONFIGARG
 		if [ $? != 0 ] ; then
-		    echo "Could not revoke certificate."
+		    echo "ERROR: Could not revoke certificate."
 		    abort 1
 		fi
 
@@ -665,10 +705,15 @@ issue_crl()
     else
 	KEYARG="-keyfile $ROOTKEYNAME -keyform engine -engine $ENGINE"
     fi
+
+    get_passphrase_cached
+    if [ ! -z ${PASSPHRASE+x} ] ; then
+	OPENSSLOPT="-passin env:PASSPHRASE"
+    fi
     
-    $HSM_PRELOAD $OPENSSL ca -gencrl -md sha1 $KEYARG $PROFILEARG -out $CRLFILE $CONFIGARG
+    $HSM_PRELOAD $OPENSSL ca -gencrl -md sha1 $KEYARG $OPENSSLOPT $PROFILEARG -out $CRLFILE $CONFIGARG
     if [ $? != 0 ] ; then
-	echo "Could not issue CRL."
+	echo "ERROR: Could not issue CRL."
 	$RM -f $CRLFILE
 	abort 1
     fi
@@ -740,7 +785,7 @@ initialize()
 	    fi
 	    ;;
 	*)
-	    echo "Engine '$ENGINE' not supported yet"
+	    echo "ERROR: Engine '$ENGINE' not supported yet"
 	    abort 1
 	    ;;
     esac
@@ -785,7 +830,7 @@ initialize()
 	echo "INFO: Existing CA will be kept as backup"
 	
 	if [ -d $ATTIC ] ; then
-	    echo "Old backup $ATTIC is in the way, please correct this."
+	    echo "ERROR: Old backup $ATTIC is in the way, please correct this."
 	    abort 1
 	fi
 	$MKDIR -p $ATTIC || abort 1
@@ -820,7 +865,7 @@ initialize()
 	$DD if=/dev/urandom of=$CA_HOME/private/.rand bs=1 count=1024
 	$CHMOD 600 $CAPRIVDIR/.rand
 	if [ "`$WC -c $CAPRIVDIR/.rand | awk '{print $1}'`" != "1024" ] ; then
-	    echo "Could not read enough random data from /dev/random, rerun this script"
+	    echo "ERROR: Could not read enough random data from /dev/random, rerun this script"
 	    abort 1
 	fi
 	echo "* Set path to random seed"
@@ -870,22 +915,27 @@ EOF
 	    CA_VALIDITY=1
 	    
 	    echo "* Absolute validity requested, creating dummy certificate to work around an"
-	    echo "  OpenSSL limitation. You will have to enter the private key PIN twice due"
-	    echo "  to this problem."
+	    echo "  OpenSSL limitation. (You may have to enter the private key PIN twice due"
+	    echo "  to this problem.)"
 	fi
     else
 	# create certificate request only
 	echo "* Generating self-signed CA root certificate with a validity of $CA_VALIDITY days"
 	OUT="$CAREQ"
     fi
-
-	# oliwel - overload environment to get a clean request
-	export CN="Root CA"
-
-    $HSM_PRELOAD $OPENSSL req -new $X509ARG -days $CA_VALIDITY $KEYARG -out $OUT $CONFIGARG
+    
+    # oliwel - overload environment to get a clean request
+    export CN="Root CA"
+    
+    get_passphrase_cached
+    if [ ! -z ${PASSPHRASE+x} ] ; then
+	OPENSSLOPT="-passin env:PASSPHRASE"
+    fi
+    
+    $HSM_PRELOAD $OPENSSL req $OPENSSLOPT -new $X509ARG -days $CA_VALIDITY $KEYARG -out $OUT $CONFIGARG
 
     if [ $? != 0 ] ; then
-	echo "Something went wrong, could not create $OUT."
+	echo "ERROR: Something went wrong, could not create $OUT."
 	abort 1
     fi
 
@@ -975,7 +1025,7 @@ backup()
 	FILENAME="$1"
     fi
     if [ -e "$FILENAME" ] ; then
-	echo "File $FILENAME already exists. Aborted."
+	echo "ERROR: File $FILENAME already exists. Aborted."
 	abort 1
     fi
     echo "Creating backup archive file $FILENAME"
@@ -994,6 +1044,7 @@ modifycnf()
 
 ######################################################################
 ######################################################################
+
 
 # CA profile to use
 PROFILE="CA_default"
